### PR TITLE
fix: back button in add account screen terminates app

### PR DESCRIPTION
**Pull request by tusharojha**
## Description

When the user taps on add account from the drawer, we were calling the `configurations_screen` with `Navigator.pushReplacement`. Therefore, the app terminates when back-pressed from the add account screen.  So, I have updated it and added an `AppBar` to show the back button with 0 elevations to match UI.

Screenshot:
temp

@harchani-ritik PTAL and suggest changes if any.

### CODE REVIEW

**Comment by harchani-ritik** [comment]
So, the second account comes on top of the first account in the navigation stack. Is this a viable behaviour? OR we could pop off the configurations screen and then replace the first account with the second account. @tusharojha @pratikbaid3 suggest, please.

**Comment by pratikbaid3** [comment]
I think the option to pop off the configuration screen and then replace the account suits better as this would probably be the desired action from the users perspective.

**Comment by tusharojha** [comment]
Although, we can replace the initial account with the new one but I think in that case we would not call it as "add account" and there will be no use of showing the list of accounts inside the drawer. 

Also, please let me know if I am misunderstanding the thing.

**Comment by harchani-ritik** [comment]
Ah, no brother, the "add account" feature is similar to adding a google account in the Gmail app. So, after a user adds another account the expected behaviour of the back button will be to close the app rather than navigating to the previous account which will be the case with your changes.

**Comment by tusharojha** [comment]
Got it!
Consider a case in which user taps on the add account button but doesn't login to another account and tries to go back. In that case rather than returning to homescreen, the app will close.

**Comment by harchani-ritik** [comment]
Yes, I guess the issue is made for handling this case only. Instead of replace, you push the conf screen on top of it. But when a user logins, it should pop off the conf screen and then replace the first account with the second account. I hope I am able to convey the requirements for this issue.

**Comment by tusharojha** [comment]
Yes I get it!
I will push new commits to this PR addressing the above discussion.

**Comment by tusharojha** [comment]
@harchani-ritik I have made the change. PTAL.

Now, if the user presses the back button from add account screen he/she will be navigated to `homescreen` rather than closing the app. If the user logs into the account successfully then also, the user gets navigated to `homescreen` with the default account switched to the newly added.

**Review by harchani-ritik — APPROVED** [review]

**Pull request merged**
