### PR TITLE
feat: Added long press to delete torrent

### PR DESCRIPTION
**Pull request by pratikbaid3**
Now the user can hold down on the torrent tile to get the popup and choose to delete
WhatsApp Image 2021-02-24 at 4 32 03 PM

#50

### CODE REVIEW

**Comment by harchani-ritik** [comment]
@pratikbaid3 
A better UI implementation for this feature would be "swipe_to_dismiss" on a torrent tile. See if you can use flutter_slidable or dismissible or any other package for the job.

**Comment by pratikbaid3** [comment]
@harchani-ritik swipe to dismiss will not show the popup to confirm deleting.

I have a better ux in mind in which the user could swipe to get options and then click to get the popup[](https://pub.dev/packages/flutter_slidable). I think that would be a better ux. Let me know if I should implement that

**Comment by pratikbaid3** [comment]
@harchani-ritik I'll implement flutter slidable

**Comment by harchani-ritik** [comment]
Yeah, and you can keep, "delete" and "delete with data" options in it on the same side, preferably on the right since 49% of the time people use the phone with one-hand.

**Comment by pratikbaid3** [comment]
WhatsApp Image 2021-02-25 at 10 58 58 AM
 @harchani-ritik I have added slide for options. If you have any preference for icons or color, let me know, ill make the changes

**Comment by harchani-ritik** [comment]
@pratikbaid3 Swiping right on the torrent tile is an action that has to support to switch to "Downloaded" tabs on the page view. So could you please implement something which would have slidable options on the left of the torrent tile while swiping right will navigate to the "Downloaded" page.

**Comment by harchani-ritik** [comment]
Also, the UI for the slidable options, keep the delete icon and text of primary colour while the background colour remains transparent or that of the scaffold.

**Comment by pratikbaid3** [comment]
WhatsApp Image 2021-03-01 at 11 53 30 AM
@harchani-ritik I have made the changes.

**Review by harchani-ritik — APPROVED** [review]

**Comment by pratikbaid3** [comment]
@harchani-ritik I have reverted the changes to now only include long press to show the popup on the list tile

**Pull request merged**
