### PR TITLE
Fixed the issue that caused the app to crash after a download has completed

### PR DESCRIPTION
**Pull request by pratikbaid3**
This was happening because the torrent object was becoming 'null' after the download has completed. Adding ternary operator prevented the crash.

### CODE REVIEW

**Comment by harchani-ritik** [comment]
@pratikbaid3 Please provide gif showing what happens now, after the download completes.

**Comment by pratikbaid3** [comment]
Untitled

**Comment by harchani-ritik** [comment]
@pratikbaid3 A better UX would be to close(pop) the torrent's details screen after the download completes.

**Comment by pratikbaid3** [comment]
Ok. Ill pop off this screen as soon as the download is completed

**Comment by pratikbaid3** [comment]
Untitled (1)
@harchani-ritik

**Comment by pratikbaid3** [comment]
#26

**Pull request closed without merging**
