### PR TITLE
new default icons for selected default labels + filter counter for overview in drawer

### PR DESCRIPTION
**Pull request by Rushour0**
**Added default label icons** 
Made a new enum type - DefaultLabels which maps to the respective png files
A new default label can be added in DefaultLabels, with its corresponding png file in assets/icons with the same name as the label

Example : 
label: videos
filename: videos.png

**Added a class DefaultPaths**
The intelli-sense can make it faster to write these paths, than having to remember them.

Example:
normal string path: assets/icons/
with DefaultPaths: DefaultPaths.defaultLabelIcons

The variable can be autocompleted with intellisense and reduces the need to remember the path if the variables are well named

solution to issue #108 
label-icon-filter-screenshot

### CODE REVIEW

**Comment by Rushour0** [comment]
New function addition in the torrent service to count the torrents by filter
All counts of the filters are now visible in the drawer
issue #109 solution

label-count-screenshot

**Comment by Rushour0** [comment]
@AbdulMalikDev can you please check with this repository?

**Comment by Rushour0** [comment]
@nb9960 can you check these updates?

**Comment by Rushour0** [comment]
@AbdulMalikDev can you review this?

**Comment by Rushour0** [comment]
@AbdulMalikDev can you please check this PR

**Comment by buildwithmalik** [comment]
@Rushour0 Please make a PR to the `develop` branch. Once we have enough changes and testing done we'll merge with `main`. Till then, I am closing this PR.

**Comment by Rushour0** [comment]
> @Rushour0 Please make a PR to the `develop` branch. Once we have enough changes and testing done we'll merge with `main`. Till then, I am closing this PR.

Alright, will do it right away

**Pull request closed without merging**
