### PR TITLE
Fixed main_screen ui issue

### PR DESCRIPTION
**Pull request by Adityabhaumik**

### CODE REVIEW

**Comment by harchani-ritik** [comment]
@Adityabhaumik Please squash your commits and provide a screenshot of the screen after the fix.

**Comment by Adityabhaumik** [comment]
Screenshot_1616043871

**Comment by Adityabhaumik** [comment]
@harchani-ritik  is it fine now?

**Review by rj-since-2000 — APPROVED** [review]
@harchani-ritik This change looks fine to me.

**Pull request merged**
