### PR TITLE
Added feature to add torrent via file explorer

### LINKED ISSUE #11: Feature to add torrent file via file explorer

### PR DESCRIPTION
**Pull request by cyber-venom003**
### New Feature: Torrent files locally saved in phone can be added on server

Fixes #11 .

Preview (There are some issues with gif recording hence it flashes 😅 )
ruTorrent_issue

### CODE REVIEW

**Comment by harchani-ritik** [comment]
Nice seems to work!
Though it throws a null exception when no file is selected, please fix it.
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'files' was called on null.
    Receiver: null
    Tried calling: files

**Comment by harchani-ritik** [comment]
@cyber-venom003 Nice seems to work!

Just add a check for null (when no file is selected) as it throws an error
```
/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'files' was called on null.
    Receiver: null
    Tried calling: files
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      AddBottomSheet.pickTorrentFile (package:rutorrentflutter/components/add_url_bottom_sheet.dart:22:26)
    <asynchronous suspension>
    #2      AddBottomSheet.build.<anonymous closure> (package:rutorrentflutter/components/add_url_bottom_sheet.dart:116:17)
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
    #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
    #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
    #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
    #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
    #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
    #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
    #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
    #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
    #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
    #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
    #16     _rootRunUnary (dart:async/zone.dart:1206:13)
    #17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #19     _invoke1 (dart:ui/hooks.dart:265:10)
    #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

**Comment by cyber-venom003** [comment]
Will see to it @harchani-ritik 👍

**Comment by cyber-venom003** [comment]
@harchani-ritik all required changes done. Please review 👀

**Pull request merged**
