### PR TITLE
feat: added validation logic in torrent/rss url

### PR DESCRIPTION
**Pull request by rj-since-2000**
Fixes #79 #73

### CODE REVIEW

**Comment by harchani-ritik** [comment]
Clicking on "Start Download" after inserting a valid URL generates this error. Please fix.

`The following NoSuchMethodError was thrown while handling a gesture:
The method 'validate' was called on null.
Receiver: null
Tried calling: validate()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _AddBottomSheetState.build.<anonymous closure> (package:rutorrentflutter/components/add_url_bottom_sheet.dart:135:43)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#58cdd
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(238.2, 522.6)
  finalLocalPosition: Offset(202.2, 17.3)
  button: 1
  sent tap down
`

**Comment by rj-since-2000** [comment]
> Clicking on "Start Download" after inserting a valid URL generates this error. Please fix.
> 
> ```The following NoSuchMethodError was thrown while handling a gesture:
> The method 'validate' was called on null.
> Receiver: null
> Tried calling: validate()
> 
> When the exception was thrown, this was the stack: 
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
> #1      _AddBottomSheetState.build.<anonymous closure> (package:rutorrentflutter/components/add_url_bottom_sheet.dart:135:43)
> #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
> #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
> ...
> Handler: "onTap"
> Recognizer: TapGestureRecognizer#58cdd
>   debugOwner: GestureDetector
>   state: ready
>   won arena
>   finalPosition: Offset(238.2, 522.6)
>   finalLocalPosition: Offset(202.2, 17.3)
>   button: 1
>   sent tap down
> ```
This wasn't there before, anyways I'll fix this

**Comment by harchani-ritik** [comment]
Yeah, it's ok, might be due to new changes.

**Comment by rj-since-2000** [comment]
> Yeah, it's ok, might be due to new changes.

fixed

**Review by harchani-ritik — APPROVED** [review]

**Pull request merged**
